return PlaceObj('ModDef', {
	'title', "BCE Outposts & Mines",
	'description', "v2.28\n-----------------------------------------------\n\n[h1]BCE Outposts & Mines[/h1]\n\n-----------------------------------------------\n\n[b]+ four additional mines[/b]\n[b]+ eleven additional outposts[/b]\n[b]+ changed income and depletion time of existing mines[/b]\n[b]+ gain profits from ganja, coca or meth business (optional additional income sources)[/b]\n[b]+ grow edibles, trade carving figures and games[/b]\n\n-----------------------------------------------\n\n\n[b]+ two additional mines[/b]\n1. Pirate Rock E4 (outpost) & Water Source E5 (mine, no depletion)\n-> harvesting of tomatoes (optional manual labor)\n-> harvesting of potatoes (optional manual labor)\n-> harvesting of wheat (optional manual labor)\n-> harvesting of herbs (optional manual labor)\n\n2. Camp Coca E12 (outpost) & Coca Plant F12 (mine, no depletion)\n-> harvesting of coca (optional manual labor)\n-> harvesting of apples (optional manual labor)\n-> harvesting of bananas (optional manual labor)\n-> harvesting of cacao (optional manual labor)\n-> production of coca (optional manual labor)\n\n3. Twin Manor L18 (no mine or outpost)\n-> deal meth (optional mod content)\n-> deal carving figures\n\n4. Quarry in I11 (mine; depletes after ~42 days)\n\n->-> [i]BCE Outposts & Mines[/i] provides extra income to the player compared to vanilla Jagged Alliance 3 in order to make up for the inceased difficulty and costs this comes with\n\n[b]+ ten additional outposts[/b]\n-> additional attacks depending on your game progress for additional difficulty\n-> increased squadsize of the attacks of the 9 new outposts (please play together with BCE Enemies to counter balance autofights and adjust the enemy squad size of existing vanilla JA3 outpost attacks accordingly)\n-> changed frequency and target recognition of all existing outposts so that outpost attacks are more likely to conquer back sectors according to your game progress and as well provide a larger variety of possible attacks\n-> final outposts provide heavily increased threat and defence to give the player an extra challenge when reaching the locations and areas of the endgame\n-> outpost attack become a lot stronger after the world flip event than before and the player has a harder time conquering them back without risking what they still own\n-> Basic Crafting Economy mod - which is requirement for BCE Outposts & Mines - increases the Biff event timer from 38 to 87 days so you have a lot more time to prepare\n-> altered routes of outpost attacks and diamond case deliveries\n\n[b]+ changed income and depletion time of existing mines[/b]\n-> several mines have their depletion time increased or put eternal, such as the one in Port Cacao\n\n[b]+ gain profits from ganja, coca or meth business (optional additional income sources)[/b]\n-> utilize your mercs for production or purchases of said trading goods\n-> utilize your mercs to channel the sales all over the map and become the coca king \n-> fully optional content for your playthrough\n-> sales locations of ganja, coca and meth are heavily supported from the mod [i]BCE Markets[/i] and it is suggested to play [i]BCE Outposts & Mines[/i] together with [i]BCE Markets[/i] to fully use this optional content\n\n-----------------------------------------------\n\n[h3]Compatibility & Requirements[/h3]\n+ requires Basic [i]Crafting Economy[/i] 4.84+\n+ requires Chinese Multitool\n+ almost requires [i]BCE Enemies[/i] mod, but left open to your decision and desire to do experiments\nhttps://steamcommunity.com/sharedfiles/filedetails/?id=3350565285\n+ suggested to play together with [i]BCE Markets[/i] to get all market places to sell your goods in the world\nhttps://steamcommunity.com/sharedfiles/filedetails/?id=3243635763\n+ not compatible with [i]Evermine[/i]\n+ semi compatible with [i]Tactical AI Project[/i] - if you want to mix this, you should in any way use BCE Enemies & Rato's Explosive Overhaul in additon and switch off all mod options of TAIP\n+ installation during an existing run can be problematic and some changes do not take effect while others will, it is suggested to start a new run\n\n-----------------------------------------------\n\n [h3]Basic Crafting Economy Collection[/h3]\n https://steamcommunity.com/sharedfiles/filedetails/?id=3169772611\n (Collection of mods that work well with BCE series)\n\n-----------------------------------------------",
	'image', "Mod/AUE3sd/Images/BCEGuns90.jpg",
	'last_changes', "v2.28\n-----------------------------------------------\n\n[h1]BCE Outposts & Mines[/h1]\n\n-----------------------------------------------\n\n[b]+ four additional mines[/b]\n[b]+ eleven additional outposts[/b]\n[b]+ changed income and depletion time of existing mines[/b]\n[b]+ gain profits from ganja, coca or meth business (optional additional income sources)[/b]\n[b]+ grow edibles, trade carving figures and games[/b]\n\n-----------------------------------------------\n\n\n[b]+ two additional mines[/b]\n1. Pirate Rock E4 (outpost) & Water Source E5 (mine, no depletion)\n-> harvesting of tomatoes (optional manual labor)\n-> harvesting of potatoes (optional manual labor)\n-> harvesting of wheat (optional manual labor)\n-> harvesting of herbs (optional manual labor)\n2. Camp Coca E12 (outpost) & Coca Plant F12 (mine, no depletion)\n-> harvesting of coca (optional manual labor)\n-> harvesting of apples (optional manual labor)\n-> harvesting of bananas (optional manual labor)\n-> harvesting of cacao (optional manual labor)\n-> production of coca (optional manual labor)\n3. Twin Manor L18 (no mine or outpost)\n-> deal meth (optional mod content)\n\n->-> [i]BCE Outposts & Mines[/i] provides extra income to the player compared to vanilla Jagged Alliance 3 in order to make up for the inceased difficulty and costs this comes with\n\n[b]+ six additional outposts[/b]\n-> additional attacks depending on your game progress for additional difficulty\n-> increased squadsize of the attacks of the 6 new outposts (please play together with BCE Enemies to counter balance autofights and adjust the enemy squad size of existing vanilla JA3 outpost attacks accordingly)\n-> changed frequency and target recognition of all existing outposts so that outpost attacks are more likely to conquer back sectors according to your game progress and as well provide a larger variety of possible attacks\n-> final outposts provide heavily increased threat and defence to give the player an extra challenge when reaching the locations and areas of the endgame\n-> outpost attack become a lot stronger after the world flip event than before and the player has a harder time conquering them back without risking what they still own\n-> Basic Crafting Economy mod - which is requirement for BCE Outposts & Mines - increases the Biff event timer from 38 to 78 days so you have a lot more time to prepare\n-> altered routes of outpost attacks and diamond case deliveries\n\n[b]+ changed income and depletion time of existing mines[/b]\n-> several mines have their depletion time increased or put eternal, such as the one in Port Cacao\n\n[b]+ gain profits from ganja, coca or meth business (optional additional income sources)[/b]\n-> utilize your mercs for production or purchases of said trading goods\n-> utilize your mercs to channel the sales all over the map and become the coca king \n-> fully optional content for your playthrough\n-> sales locations of ganja, coca and meth are heavily supported from the mod [i]BCE Markets[/i] and it is suggested to play [i]BCE Outposts & Mines[/i] together with [i]BCE Markets[/i] to fully use this optional content\n\n-----------------------------------------------\n\n[h3]Compatibility & Requirements[/h3]\n+ requires Basic [i]Crafting Economy[/i] 4.84+ (best 5.00+)\n+ requires Chinese Multitool\n+ almost requires [i]BCE Enemies[/i] mod, but left open to your decision and desire to do experiments\nhttps://steamcommunity.com/sharedfiles/filedetails/?id=3350565285\n+ suggested to play together with [i]BCE Markets[/i] to get all market places to sell your goods in the world\nhttps://steamcommunity.com/sharedfiles/filedetails/?id=3243635763\n+ not compatible with [i]Evermine[/i]\n+ semi compatible with [i]Tactical AI Project[/i] - if you want to mix this, you should in any way use BCE Enemies & Rato's Explosive Overhaul in additon and switch off all mod options of TAIP\n+ installation during an existing run can be problematic and some changes do not take effect while others will, it is suggested to start a new run\n\n-----------------------------------------------\n\n [h3]Basic Crafting Economy Collection[/h3]\n https://steamcommunity.com/sharedfiles/filedetails/?id=3169772611\n (Collection of mods that work well with BCE series)\n\n-----------------------------------------------",
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "E554EN",
			'title', "Basic Crafting Economy",
			'version_major', 5,
			'version_minor', 16,
		}),
		PlaceObj('ModDependency', {
			'id', "cHrLTFM",
			'title', "Chinese Multitool",
			'version_major', 1,
			'version_minor', 3,
		}),
	},
	'id', "AUE3sd",
	'author', "whahappen",
	'version_major', 2,
	'version_minor', 28,
	'version', 1930,
	'lua_revision', 233360,
	'saved_with_revision', 366685,
	'code', {
		"Code/BCE_Outposts_Squads.lua",
		"Code/BCE_Agency_Squads.lua",
		"Code/BCE_LegionAttackers.lua",
	},
	'default_options', {},
	'has_data', true,
	'saved', 1779354035,
	'code_hash', 2013127003203155615,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "SectorTravelTime",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "SectorTravelTimeBase",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "SectorTravelTimeDiamonds",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "SectorTravelTimeEnemy",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "SectorTravelTimeWater",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "RoadTravelTimeMod",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_E4",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_E5",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_E12",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_F12",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H4",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_F7",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_G10",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_D10",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H14",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_E16",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_A20",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_F19",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_K16",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_B5",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_B9",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J12",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_L12",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_L19",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I19",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_B18",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_C15",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J8",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_A2",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H7",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_K10",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_C7_Underground",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_B12",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_D18",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I18",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I11",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_A8",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I10",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "DeadRockLootCrate_01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "DeadRockLootCrate_01_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "DeadRockLootCrate_01_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "DeadRockLootCrate_01_RNG3",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "DeadRockLootCrate_02",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "DeadRockLootCrate_02_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "DeadRockLootCrate_03",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "DeadRockLootCrate_04",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "DeadRockLootCrate_05",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Chalet_Mine_01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Chalet_Mine_02",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Chalet_Mine_03",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Chalet_Mine_03_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Chalet_Mine_03_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Chalet_Mine_03_RNG2_A",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Chalet_Mine_04",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Chalet_Outpost_01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Chalet_Outpost_01_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Chalet_Outpost_01_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Chalet_Outpost_02",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Chalet_Outpost_02_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Chalet_Outpost_03",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Chalet_Outpost_04",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Chalet_Outpost_05",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Chalet_Outpost_06",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Chalet_Outpost_Tree",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Chalet_Outpost_Tree_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Chalet_Outpost_Tree_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "PitStop_LootCrate01Guns",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "PitStop_LootCrate02Drugs",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "PitStop_LootCrate02Drugs_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "PitStop_LootCrate03Clothing",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "PitStop_LootCrate04Metals",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "PitStop_LootCrate05NiceArmorUps",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "PitStop_LootCrate06NiceWeaponUps",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "PitStop_LootCrate07HiddenLoot1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "PitStop_LootCrate07HiddenLoot1_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "PitStop_LootCrate07HiddenLoot1_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "PitStop_LootCrate08HiddenLoot2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "PitStop_LootCrate09Food01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "PitStop_LootCrate10Food02",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "PitStop_LootCrate09Food01_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "PitStop_LootCrate09Food01_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "PitStop_LootCrate10Chemicals",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "PitStop_LootCrate11GlassRocks",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "E16Outpost_LootCrate01Guns",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "E16Outpost_LootCrate02NiceWeaponUps",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "DesertOutpostCrate",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "G10OutpostCrate",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "D10Outpost_Crate01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "D10Outpost_Crate01_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "D10Outpost_Crate01_RNG1_A",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "D10Outpost_Crate01_RNG1_B",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "D10Outpost_Crate01_RNG1_C",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "D10Outpost_Crate01_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "D10Outpost_Crate01_RNG2_A",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "D10Outpost_Crate01_RNG2_B",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "D10Outpost_Crate01_RNG3",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "D10Outpost_Crate02",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "H14Outpost_Crate01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "H14Outpost_Crate01_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "H14Outpost_Crate01_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "A20Outpost_Crate01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "A20Outpost_Crate02",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "A20Outpost_Crate03",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "F19Outpost_Crate01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "F19Outpost_Crate02",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "F19Outpost_Crate03",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "F19Outpost_Crate04",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "F19Outpost_Crate05",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "F19Outpost_Crate06",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "F19Outpost_Crate07",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "F19Outpost_Crate07_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "F19Outpost_Crate07_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "F19Outpost_Crate08",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "F19Outpost_Crate08_RNG0",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "F19Outpost_Crate08_RNG0B",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "F19Outpost_Crate08_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "F19Outpost_Crate08_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "F19Outpost_Crate09",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "F19Outpost_Crate09_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "F19Outpost_Crate09_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "K16Outpost_Crate01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "K16Outpost_Crate01_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "K16Outpost_Crate02",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "K16Outpost_Crate02_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "K16Outpost_Crate02_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "LockboxesDual_OutpostMinesMod_RNG0",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "LockboxesSingle__OutpostsMinesMod_RNG0",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "LockboxesDual_RNG01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "LockboxesDual_RNG02",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "LockboxesDual_RNG03",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "LockboxesDual_RNG04",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "LockboxesDual_RNG05",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "LockboxesDual_RNG06",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "LockboxesDual_RNG07",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "LockboxesDual_RNG08",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "LockboxesDual_RNG09",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "LockboxesDual_RNG10",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_K10PortCacaoDocks01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_K10PortCacaoDocks02",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_K10PortCacaoDocks02_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_K10PortCacaoDocks02_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_K10PortCacaoDocks02_RNG3",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_K10PortCacaoDocks03",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_K10PortCacaoDocks03_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_K10PortCacaoDocks03_RNG1_A",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_K10PortCacaoDocks03_RNG1_B",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_K10PortCacaoDocks03_RNG1_C",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_K10PortCacaoDocks04",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_K10PortCacaoDocks04_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B12LandsbachMine01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B12LandsbachMine01_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B12LandsbachMine01_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_I18Wassergrab",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B18Matrix01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B18Matrix01_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B18Matrix01_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B18Matrix02",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B18Matrix03",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B18Matrix04",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B18Matrix04_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B18Matrix05",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B18Matrix05_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B18Matrix05_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B18Matrix06",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B18Matrix06_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B18Matrix06_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B18Matrix06_RNG3",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B18Matrix07",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B18Matrix07_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B18Matrix07_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B18Matrix08_largeBox",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B18Matrix08_largeBox_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B18Matrix08_RNG1_A",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "JungleCamp_Loot01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "JungleCamp_Loot01_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "JungleCamp_Loot02",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "JungleCamp_Loot03",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_DesertA2Mine_01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_DesertA2Mine_01_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_DesertA2Mine_01_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_DesertA2Mine_02",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_DesertA2Mine_02_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_DesertA2Mine_02_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_DesertA2Mine_02_RNG3",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_H4Outpost",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_H4Outpost_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_H4Outpost_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_H4Outpost_RNG3",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B5Outpost_Crate01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B5Outpost_Crate02",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B5Outpost_Crate02_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B5Outpost_Crate03",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B5Outpost_Crate03_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B5Outpost_Crate04_Food",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B5Outpost_Crate04_Food_1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B5Outpost_Crate04_Food_2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B5Outpost_Crate04_Food_3",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B5Outpost_Crate04_Food_4",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_B5Outpost_Crate04_Food_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_L12Outpost_Crate01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_L12Outpost_Crate01_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_L12Outpost_Crate02",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_L12Outpost_Crate02_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_L12Outpost_Crate03",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_L12Outpost_Crate03_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_L12Outpost_Crate04",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_L12Outpost_Crate04_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_L12Outpost_Crate05_Prop",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_I11Quarry_Crate01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_I11Quarry_Crate01_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_I11Quarry_Crate02",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_H7FleatownMine01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_H7FleatownMine01_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_H7FleatownMine01_RNG1_A",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_H7FleatownMine01_RNG1_B",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_H7FleatownMine01_RNG1_C",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_H7FleatownMine01_RNG1_D",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_H7FleatownMine01_RNG1_E",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_H7FleatownMine01_RNG1_F",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_H7FleatownMine01_RNG1_G",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_C15OutpostLoot01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_C15OutpostLoot02",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_C15OutpostLoot03",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_A8BiffMine01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_A8BiffMine01_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_A8BiffMine01_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_A8BiffMine01_RNG3",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_A8BiffMine01_RNG4",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_A8BiffMine02",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_J8Outpost01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_J8Outpost01_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_J8Outpost01_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_J8Outpost01_RNG4",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_J8Outpost02",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_J8Outpost02_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_J8Outpost02_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_J8Outpost02_RNG3",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_J8Outpost03",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_LootBoxes_J8Outpost03_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_Loot_GovernmentContractorCrate01",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_Loot_GovernmentContractorCrate01_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_Loot_GovernmentContractorCrate02",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "BCE_SO_CocaCraftingF12",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "BCE_SO_MethCraftingL18",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "BCE_SO_Harvest0XCampCocaE12",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "BCE_SO_HarvestCampCocaE12_Apples",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "BCE_SO_HarvestCampCocaE12_Bananas",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "BCE_SO_HarvestCampCocaE12_Oranges",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "BCE_SO_HarvestCampCocaE12_Lemons",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "BCE_SO_HarvestCampCocaE12_Cacao",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "BCE_SO_HarvestSecretWaterSourceE5_01",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "BCE_SO_HarvestSecretWaterSourceE5_02",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "BCE_SO_HarvestSecretWaterSourceE5_03",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "BCE_SO_HarvestSecretWaterSourceE5_04",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "BCE_SO_ExtractRocksQuarryI11",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "BCE_SO_Harvest02Outpost_Backup",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_HarvestCoca",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_HarvestApple",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_HarvestBanana",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_HarvestOrange",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_HarvestLemons",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_HarvestCacaoatCampCoca",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "BCE_Craft_Coca01CampCoca",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "BCE_Craft_MedicalSerum_CampCoca",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_HarvestGanja",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_HarvestPotato",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_HarvestTomato",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_HarvestWheat",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_ExtractRocks",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_ExtractRocks_RNG1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_ExtractRocks_RNG2",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_ExtractRocks_RNG3",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "BCE_ExtractRocks_RNG4",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "BCE_Craft_MethL18",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "BCE_TradingGold_Dollars6000carving1",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "BCE_TradingGold_Dollars6000carving2",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "BCE_TradingGold_Dollars6000carving3",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "BCE_TradingGold_CarvingCollection",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "BCE_TradingGold_Dollars16000BluntsBox",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "BCE_TradingGold_Dollars2000LemonHaze",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "BCE_TradingGold_Dollars2000OrangeBud",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "BCE_TradingGold_GoldGamesCollection",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "BCE_TEMPL_Harvest0X_CampCoca",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "BCE_TEMPL_Harvest0X_CampCocaApple",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "BCE_TEMPL_Harvest0X_CampCocaBanana",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "BCE_TEMPL_Harvest0X_CampCocaOrange",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "BCE_TEMPL_Harvest0X_CampCocaLemons",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "BCE_TEMPL_Harvest0X_CampCocaCacao",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "BCE_TEMPL_Harvest0X_SecretWaterSourceGanja",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "BCE_TEMPL_Harvest0X_SecretWaterSourcePotato",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "BCE_TEMPL_Harvest0X_SecretWaterSourceTomato",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "BCE_TEMPL_Harvest0X_SecretWaterSourceWheat",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "BCE_TEMPL_Harvest0X_QuarryRocks",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
	},
	'steam_id', "3378968662",
	'TagBalancing&Difficulty', true,
	'TagEnemies', true,
	'TagMines&Economy', true,
	'TagOther', true,
	'TagQuest&Campaigns', true,
	'TagSatview&Operations', true,
})